controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

indexcontroller:
    path: /index
    controller: App\Controller\IndexController::indexAction